name: Release

on:
  release:
    types: [published]

jobs:
  build:
    if: github.repository == 'NorskHelsenett/HelseID.Library'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: | 
            8.0.x
            9.0.x
      - name: Build projects
          dotnet build HelseId.Library/HelseId.Library.csproj -c Release
          dotnet build HelseId.Library.ClientCredentials/HelseId.Library.ClientCredentials.csproj -c Release
          dotnet build HelseId.Library.Mocks/HelseId.Library.Mocks.csproj -c Release
          dotnet build HelseId.Library.Selvbetjening/HelseId.Library.Selvbetjening.csproj -c Release
      - name: Build NuGet Packages
        run: |
          dotnet pack HelseId.Library/HelseId.Library.csproj -c Release
          dotnet pack HelseId.Library.ClientCredentials/HelseId.Library.ClientCredentials.csproj -c Release
          dotnet pack HelseId.Library.Mocks/HelseId.Library.Mocks.csproj -c Release
          dotnet pack HelseId.Library.Selvbetjening/HelseId.Library.Selvbetjening.csproj -c Release
      - name: Push NuGet Packages
        run: |
          dotnet nuget push HelseId.Library/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }}
          dotnet nuget push HelseId.Library.ClientCredentials/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }}
          dotnet nuget push HelseId.Library.Mocks/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }}
          dotnet nuget push HelseId.Library.Selvbetjening/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }}
